# Generated by Django 4.2 on 2023-04-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/book_images/'),
            preserve_default=False,
        ),
    ]
