# Generated by Django 4.2 on 2023-04-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
