# Generated by Django 4.2 on 2023-04-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.PositiveIntegerField()),
                ('borrowed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lost', models.BooleanField(default=False)),
                ('lost_date', models.DateField(blank=True, null=True)),
                ('damaged', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('removed_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
