# Generated by Django 4.2 on 2023-04-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_bookcopy_delete_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcopy',
            old_name='borrowed',
            new_name='rented',
        ),
    ]
