# Generated by Django 4.2 on 2023-04-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='copy_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
