# Generated by Django 4.2 on 2023-04-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_bookcopy_copy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='books',
        ),
        migrations.AddField(
            model_name='rental',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
            preserve_default=False,
        ),
    ]
