# Generated by Django 4.2 on 2023-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='copy_number',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
