# Generated by Django 4.2 on 2023-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_bookcopy_copy_number_bookcopy_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
