# Generated by Django 4.2 on 2023-05-12 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_bookcopy_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
