# Generated by Django 4.2 on 2023-05-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_bookcopy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='rented',
        ),
    ]
