# Generated by Django 4.2 on 2023-05-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_bookcopy_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
