# Generated by Django 4.2 on 2023-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_bookcopy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='sku',
            field=models.CharField(default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
