# Generated by Django 4.2 on 2023-05-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_bookcopy_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='sku',
        ),
    ]
