# Generated by Django 4.2 on 2023-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_bookcopy_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='sku',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
